// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Zn2INlro5YSGwRjw0C1LQSAC35tOJCU',
    appId: '1:731030836965:web:9e36ffb4674eeeca9ee60c',
    messagingSenderId: '731030836965',
    projectId: 'flutter-signin-f2ace',
    authDomain: 'flutter-signin-f2ace.firebaseapp.com',
    storageBucket: 'flutter-signin-f2ace.firebasestorage.app',
    measurementId: 'G-KY9KHQ9KX3',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcyrfqxUqDM0gN1bnQ6xUAKUIlMzryaHc',
    appId: '1:731030836965:android:bbb2c44feda223609ee60c',
    messagingSenderId: '731030836965',
    projectId: 'flutter-signin-f2ace',
    storageBucket: 'flutter-signin-f2ace.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAORIfQM9TGCQLnYvgViFDhSpAzpm5juY',
    appId: '1:731030836965:ios:7ef4c1ad647c45479ee60c',
    messagingSenderId: '731030836965',
    projectId: 'flutter-signin-f2ace',
    storageBucket: 'flutter-signin-f2ace.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAORIfQM9TGCQLnYvgViFDhSpAzpm5juY',
    appId: '1:731030836965:ios:7ef4c1ad647c45479ee60c',
    messagingSenderId: '731030836965',
    projectId: 'flutter-signin-f2ace',
    storageBucket: 'flutter-signin-f2ace.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Zn2INlro5YSGwRjw0C1LQSAC35tOJCU',
    appId: '1:731030836965:web:a2a3910af010a3209ee60c',
    messagingSenderId: '731030836965',
    projectId: 'flutter-signin-f2ace',
    authDomain: 'flutter-signin-f2ace.firebaseapp.com',
    storageBucket: 'flutter-signin-f2ace.firebasestorage.app',
    measurementId: 'G-7SC6F8FB31',
  );
}
